<a href="https://colab.research.google.com/github/Sam2415-gif/Goeduhub/blob/main/TASK4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 4

Name - SAMMOHAN PRADHAN

Reg no. - 11529



Q1. Import the numpy package under the name np and Print the numpy version and the configuration.

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Q2. Create a null vector of size 10

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Q3. Create Simple 1-D array and check type and check data types in array

In [3]:
a = np.array([10,20,30])
print(a)
print(a.dtype)

[10 20 30]
int64


Q4. How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
import sys
y = np.array([1,2,3,4,5,6])
print('Dimension of array is: ',y.size)
print('Bytes per element is: ',y.itemsize)
print('Bytes of memory used: ',y.nbytes)

Dimension of array is:  6
Bytes per element is:  8
Bytes of memory used:  48


Q5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
x = np.zeros(10)
print(x)
print('Update fifth value to 1')
x[5]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Q6. Create a vector with values ranging from 10 to 49

In [6]:
z = np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Q7. Reverse a vector (first element becomes last)

In [7]:
m = np.arange(0,10)
print('Original vector: ',m)
m = m[::-1]
print('Reverse vector: ',m)

Original vector:  [0 1 2 3 4 5 6 7 8 9]
Reverse vector:  [9 8 7 6 5 4 3 2 1 0]


Q8. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
t = np.arange(0,9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
n = [1,2,0,0,4,0]
print('Indices of non-zero elements are: ',np.nonzero(n))

Indices of non-zero elements are:  (array([0, 1, 4]),)


Q10. Create a 3x3 identity matrix

In [10]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q11. Create a 3x3x3 array with random values

In [11]:
x = np.random.random((3,3,3))
print(x)

[[[0.42341934 0.65167392 0.67041893]
  [0.70026573 0.74811481 0.11234815]
  [0.12439624 0.7250351  0.18874335]]

 [[0.94142064 0.56568594 0.24454457]
  [0.58269062 0.05578546 0.12007751]
  [0.18666685 0.02579343 0.1692124 ]]

 [[0.30328141 0.11281828 0.15171084]
  [0.94888457 0.02313933 0.50555839]
  [0.35513409 0.72705494 0.74785828]]]


Q12. Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
x = np.random.random((10,10))
print(x)
print('Minimum value of the array is: ',x.min())
print('Maximum value of the array is: ',x.max())

[[0.69981192 0.02772532 0.78673494 0.69155452 0.83321435 0.22276006
  0.73067888 0.403407   0.10297807 0.89206953]
 [0.20351793 0.15124024 0.76593353 0.27899578 0.01679005 0.86554079
  0.8422208  0.88918182 0.76570967 0.42533141]
 [0.72201145 0.57925422 0.38281542 0.31325683 0.42252027 0.95108459
  0.85633727 0.53935994 0.04913607 0.490189  ]
 [0.60327664 0.49157846 0.87635029 0.19267474 0.31195283 0.10486672
  0.51427036 0.71603025 0.44703854 0.17477677]
 [0.57862904 0.72417746 0.64817455 0.39034454 0.66478903 0.83522881
  0.65654271 0.36186044 0.15794303 0.32898042]
 [0.38263818 0.78688059 0.24663477 0.82562307 0.52374587 0.22346107
  0.02533266 0.39308325 0.3642359  0.19313809]
 [0.47770764 0.17526362 0.47139239 0.32838122 0.17522801 0.5131135
  0.44174982 0.9913306  0.69999832 0.09140348]
 [0.87576051 0.7291928  0.60336871 0.20837923 0.87366144 0.54107254
  0.36931192 0.79292231 0.04857319 0.28359243]
 [0.5574154  0.15838128 0.55269128 0.98343091 0.49650699 0.1807067
  0.68950555 0

Q13. Create a random vector of size 30 and find the mean value

In [13]:
x = np.random.random((30))
print(x)
print('Mean value of the random vector is: ',x.mean())

[0.9000195  0.18197537 0.16269188 0.14864321 0.22894485 0.44854623
 0.36740517 0.87657102 0.70098767 0.05312439 0.70130027 0.10211496
 0.15152158 0.79228065 0.58037674 0.932331   0.90368655 0.23159775
 0.70954654 0.0247822  0.50783132 0.40142564 0.66654594 0.7018574
 0.09848827 0.92641487 0.82716685 0.84491665 0.03363759 0.37019579]
Mean value of the random vector is:  0.48589759498464313


Q14. Create a 2d array with 1 on the border and 0 inside

In [14]:
x = np.ones((7,7))
print('Original array: ')
print(x)
x[1:-1,1:-1]=0
print('2d array with 1 on the border and 0 inside: ')
print(x)

Original array: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
2d array with 1 on the border and 0 inside: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Q15. How to add a border (filled with 0's) around an existing array?

In [15]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

In [16]:
a = np.arange(1,15).reshape(2,7)
print(a)

#Get 13
print(a[1,5])

#Get first row only
print(a[0])

#Get 3rd column only
print(a[:,2])

#Get [2,4,6]
print([a[0,1],a[0,3],a[0,5]])

#Replace 13 by 20
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2, 4, 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Q17. How to Convert a 1D array to a 2D array with 2 rows?

In [17]:
a = np.arange(10)
print('1D array:')
print(a)
a = a.reshape(2,5)
print('2D array with 2 rows:')
print(a)

1D array:
[0 1 2 3 4 5 6 7 8 9]
2D array with 2 rows:
[[0 1 2 3 4]
 [5 6 7 8 9]]


Q18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q19. Write a program to show how Numpy taking less memory compared to Python List?

In [19]:
import sys

l = range(100)
print('Size of each element of list in bytes: ',sys.getsizeof(l))
print('Size of the whole list in bytes: ',sys.getsizeof(l)*len(l))

a = np.arange(100)
print('Size of each element in the Numpy array in bytes: ',a.itemsize)
print('Size of the whole Numpy array in bites: ',a.itemsize*a.size)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  4800
Size of each element in the Numpy array in bytes:  8
Size of the whole Numpy array in bites:  800


Q20. Write a program to show how Numpy taking less time compared to Python List?

In [20]:
import sys
import time

size = 1000000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('Time taken by lists:')
print((time.time()-start)*1000)

#numpy array
start = time.time()
result1 = n1+n2
print('Time taken by numpy arrays')
print((time.time()-start)*1000)

Time taken by lists:
121.1390495300293
Time taken by numpy arrays
3.483295440673828
